# Generated by Django 3.2.7 on 2021-09-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMercadoLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('token_type', models.CharField(max_length=100)),
                ('expires_in', models.IntegerField()),
                ('scope', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserMercadoLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_secret', models.CharField(max_length=50)),
                ('redirect_uri', models.URLField()),
            ],
        ),
    ]
