# Generated by Django 3.2.7 on 2021-09-20 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usermercadolibre_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmercadolibre',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When we received the event.'),
            preserve_default=False,
        ),
    ]
