# Generated by Django 3.2.7 on 2021-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210920_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSellMercadoLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_mercadolibre', models.IntegerField()),
                ('item_name_mercadolibre', models.CharField(max_length=300)),
                ('item_quatity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=9)),
            ],
        ),
    ]
