# Generated by Django 3.2.7 on 2021-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210921_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsellmercadolibre',
            name='payment_id',
            field=models.CharField(max_length=300),
        ),
    ]
