# Generated by Django 3.2.7 on 2021-10-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_itemsellmercadolibre_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsellmercadolibre',
            name='brand',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsellmercadolibre',
            name='model',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsellmercadolibre',
            name='part_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
